name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci --force
      - name: build project
        run: npm run build:prod
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        if: always()
        run: npm run storybook:build
      - name: screenshot testing
        if: always()
        run: npm run test:ui:ci
